
UNIVERSITES_FR =  {
    'Aix-Marseille': 'univ-amu.fr',
    'Albi': 'univ-jfc.fr',
    'Amiens': 'u-picardie.fr',
    'Angers': 'univ-angers.fr',
    'Antilles': 'univ-ag.fr',
    'Arras': 'univ-artois.fr',
    'Avignon': 'univ-avignon.fr',
    'Belfort': 'utbm.fr',
    'Besançon': 'univ-fcomte.fr',
    'Bordeaux Montaigne': 'u-bordeaux-montaigne.fr',
    'Bordeaux': 'u-bordeaux.fr',
    'Brest': 'univ-brest.fr',
    'Caen' : 'unicaen.fr',
    'Cergy': 'cyu.fr',
    'Chambéry': 'univ-smb.fr',
    'Clermont-Ferrand': 'uca.fr',
    'Compiègne': 'utc.fr',
    'Corte': 'universita.corsica',
    'Creteil': 'u-pec.fr',
    'Dijon': 'u-bourgogne.fr',
    'Dunkerque': 'univ-littoral.fr',
    'Evry': 'univ-evry.fr',
    'Grenoble': 'univ-grenoble-alpes.fr',
    'Guyane': 'univ-guyane.fr',
    'La Réunion': 'univ-guyane.fr',
    'La Rochelle': 'univ-larochelle.fr',
    'Le Havre': 'univ-lehavre.fr',
    'Le Mans': 'univ-lemans.fr',
    'Lille': 'univ-lille.fr',
    'Limoges': 'unilim.fr',
    'Lyon Claude Bernard': 'univ-lyon1.fr',
    'Lyon Lumière': 'univ-lyon2.fr',
    'Lyon Jean Moulin': 'univ-lyon3.fr',
    'Marne-la-Vallée': 'univ-gustave-eiffel.fr',
    'Mayotte': 'univ-mayotte.fr',
    'Montpellier': 'umontpellier.fr',
    'Montpellier - Paul Valery': 'univ-montp3.fr',
    'Mulhouse': 'uha.fr',
    'Nancy/Metz': 'univ-lorraine.fr',
    'Nanterre': 'parisnanterre.fr',
    'Nantes:': 'univ-nantes.fr',
    'Nice': 'univ-cotedazur.fr',
    'Nîmes': 'unimes.fr',
    'Nouvelle Calédonie': 'unc.nc',
    'Orléans': 'univ-orleans.fr',
    'Paris Panthéon Assas':'u-paris2.fr',
    'Paris Pantheon Sorbonne': 'pantheonsorbonne.fr',
    'Sorbonne Paris Nord': 'univ-paris13.fr',
    'Paris 8 Vincenne':  'univ-paris8.fr',
    'Paris Cité': 'u-paris.fr',
    'Paris Saclay': 'universite-paris-saclay.fr',
    'Paris Dauphine': 'dauphine.psl.eu',
    'Paris Sorbonne': 'sorbonne-universite.fr',
    'Paris Sorbonne Nouvelle': 'univ-paris3.fr',
    'Paris PSL': 'psl.eu',
    'Pau': 'univ-pau.fr',
    'Perpignan': 'univ-perp.fr',
    'Poitiers': 'univ-poitiers.fr',
    'Polynésie': 'upf.pf',
    'Reims': 'univ-reims.fr',
    'Rennes 1': 'univ-rennes1.fr',
    'Rennes 2': 'univ-rennes2.fr',
    'Rouen': 'univ-rouen.fr',
    'Saint-Étienne':  'univ-st-etienne.fr', 
    'Strasbourg': 'unistra.fr',
    'Toulon': 'univ-tln.fr',
    'Toulouse Paul Sabatier': 'univ-tlse3.fr',
    'Toulouse Capitole': 'ut-capitole.fr',
    'Toulouse Jean Jaurès': 'univ-tlse2.fr',
    'Tour': 'univ-tours.fr',
    'Troye': 'utt.fr',
    'Valenciennes': 'uphf.fr',
    'Vannes/Lorient': 'univ-ubs.fr',
    'Versailles ': 'uvsq.fr',
    }

UNIVERSITES_HORS_FR = {
    'Louvain': 'uclouvain.be',
    'Bruxelles': 'ulb.be',
    'U Lausane': 'unil.ch',
    'EPFL': 'epfl.ch',
    'U. laval': 'ulaval.ca',
    'Montréal': 'uqam.ca',
}


EPST = {
    'CNRS': 'cnrs.fr',
    'INRAE': 'inrae.fr',
    'INRIA': 'inria.fr',
    'INSERM': 'inserm.fr',
    'IRD': 'ird.fr',
          }
